# Generated by Django 6.0 on 2026-01-04 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creneau',
            name='nombre_joueur',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
