# Generated by Django 5.2.7 on 2026-06-16 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_alter_creneau_nombre_joueur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salle',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='salle',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
